INSERT INTO courses (name)
VALUES ('Pediatrics'),
       ('Surgical diseases'),
       ('Infectious diseases'),
       ('General surgery and anesthesiology'),
       ('Orthodontics'),
       ('Mathematical programming methods'),
       ('Excel Science'),
       ('Economic geography and world history'),
       ('Demography'),
       ('Geography of tourism'),
       ('Theory of algorithms'),
       ('Software Design Methods'),
       ('Physics'),
       ('Advanced C++'),
       ('Diseases of the hard tissues of the teeth');

INSERT INTO groups (name, speciality, year)
VALUES ('FK-40', '122 Computer science', 3),
       ('TF-44', '121 Software engineering', 2),
       ('LB-03', '242 Tourism', 1),
       ('XA-67', '221 Dentistry', 5),
       ('OP-11', '222 Medicine', 2);

INSERT INTO people (first_name, last_name)
VALUES ('Seth', 'Hall'),
       ('Stella', 'White'),
       ('Daisy', 'Thomas'),
       ('Miles', 'Robinson'),
       ('Jorge', 'Walker'),
       ('Gilbert', 'Lewis'),
       ('Miles', 'Smith'),
       ('Gilbert', 'Johnson'),
       ('Gilbert', 'Wright'),
       ('Loretta', 'Taylor'),
       ('Vera', 'Jones'),
       ('Dan', 'Hill'),
       ('Roberto', 'Green'),
       ('Ramon', 'Walker'),
       ('Tracey', 'Roberts'),
       ('Dave', 'Wright'),
       ('Miles', 'Thomas'),
       ('Lucy', 'Brown'),
       ('Tracey', 'Taylor'),
       ('Lucy', 'Wright'),
       ('Gilbert', 'Smith'),
       ('Gilbert', 'Walker'),
       ('Miles', 'Green'),
       ('Tracey', 'Edwards'),
       ('Roberto', 'Green'),
       ('Loretta', 'Green'),
       ('Tracey', 'Wilson'),
       ('Brian', 'Johnson'),
       ('Ramon', 'Green'),
       ('Seth', 'Wright'),
       ('Roberto', 'Smith'),
       ('Brian', 'Robinson'),
       ('Loretta', 'White'),
       ('Brian', 'Green'),
       ('Lucy', 'Smith'),
       ('Loretta', 'Green'),
       ('Isabel', 'Harris'),
       ('Isabel', 'Roberts'),
       ('Brian', 'Jones'),
       ('Dave', 'Green'),
       ('Brian', 'Thomas'),
       ('Molly', 'Harris'),
       ('Brian', 'Walker'),
       ('Brian', 'Edwards'),
       ('Roberto', 'Williams'),
       ('Isabel', 'Roberts'),
       ('Debra', 'Hall'),
       ('Ramon', 'Roberts'),
       ('Seth', 'Smith'),
       ('Stella', 'Jones'),
       ('Daisy', 'Harris'),
       ('Brian', 'Thomas'),
       ('Daisy', 'Wright'),
       ('Brian', 'Johnson'),
       ('Isabel', 'Green'),
       ('John', 'Lewis'),
       ('Ramon', 'Williams'),
       ('Lucy', 'Harris'),
       ('Dan', 'Williams'),
       ('Loretta', 'Roberts'),
       ('Molly', 'Green'),
       ('Tracey', 'Thomas'),
       ('Lucy', 'Green'),
       ('Debra', 'Hill'),
       ('Daisy', 'Williams'),
       ('Gilbert', 'Harris'),
       ('Lucy', 'Walker'),
       ('Dan', 'Johnson'),
       ('Gilbert', 'Walker'),
       ('Loretta', 'Taylor'),
       ('Debra', 'White'),
       ('Ramon', 'Brown'),
       ('Dan', 'White'),
       ('Miles', 'Wright'),
       ('Dan', 'Brown'),
       ('John', 'Roberts'),
       ('Lucy', 'Wilson'),
       ('Lucy', 'Brown'),
       ('Jorge', 'Harris'),
       ('Jorge', 'Thomas'),
       ('Jorge', 'Harris'),
       ('Gilbert', 'Williams'),
       ('Miles', 'Walker'),
       ('Dave', 'Walker'),
       ('Miles', 'Green'),
       ('Seth', 'Harris'),
       ('Dave', 'White'),
       ('Loretta', 'Wright'),
       ('Daisy', 'Johnson'),
       ('Ramon', 'Brown'),
       ('Lucy', 'Hall'),
       ('Miles', 'Hall'),
       ('Lucy', 'Wright'),
       ('Jorge', 'Harris'),
       ('Debra', 'White'),
       ('Dave', 'Wright'),
       ('Ramon', 'White'),
       ('John', 'Hall'),
       ('Miles', 'Robinson'),
       ('John', 'Wilson'),
       ('Lucy', 'White'),
       ('Tracey', 'Roberts'),
       ('Isabel', 'Harris'),
       ('Miles', 'Jones'),
       ('Dave', 'Roberts'),
       ('Vera', 'Green'),
       ('Vera', 'Thomas'),

       ('Lucy', 'Taylor'),
       ('Brian', 'Wilson'),
       ('Dan', 'Taylor'),
       ('Miles', 'Wright'),
       ('Molly', 'Roberts');